version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: celsopires/avancando-com-go-lang
    container_name: app
    volumes:
      - .:/go/src/
    tty: true